datasets:
  raw:
    mmx:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/mmx/lowes_data.csv
      driver_params: {}


  cleaned:
    mmx:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/mmx/activity.parquet
      driver_params: {}


  processed:
    mmx:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/mmx/sales_processed.parquet
      driver_params: {}
